### PR TITLE
[WIP]Added devserver feature on zwallet

### PR DESCRIPTION
**Pull request by cnlangzi**
link to https://github.com/0chain/blobber/issues/145

### CODE REVIEW

**Review by avanaur — CHANGES_REQUESTED** [review]
The changes for `StartDevServer` on `gosdk` is not yet there. Need to understand how the devserver is gonna work and help ease on development.

**Comment by cnlangzi** [comment]
> The changes for `StartDevServer` on `gosdk` is not yet there. Need to understand how the devserver is gonna work and help ease on development.
It will run 0dns, sharder and miner mock server on local. Any request can be configured in ./config/devserver.yml.
It is improving , I will provider full documentation once it is done. thanks.

**Comment by guruhubb** [comment]
./zwallet faucet can give out more tokens than just one.
 ./zwallet faucet --methodName pour --input "need token" --tokens 2 will give out 2 tokens

**Review by Sriep — APPROVED** [review]

**Comment by cnlangzi** [comment]
ignore it first . thanks.

**Pull request closed without merging**
