### PR TITLE
`create-wallet` cli command + code cleanup

### LINKED ISSUE #150: Add `wallet-create` command to generate new wallet
We need to have the command to generate new wallets, we don't need to save the wallet to disk to avoid corrupting the existing wallet file by accident, which is a disaster if the user did not backup their wallet seed. So print the wallet info to console and users could copy that info and save to any places they want. 

Anyway, we can have option to enable saving the wallet to disk (~/.znc/) folder, but that would require us to check if the same wallet file name exists before saving, we will also need to generate wallet with random file name base on the creation date, etc. So to keep it simple, we can just ignore this option support atm.

### PR DESCRIPTION
**Pull request by bisakhmondal**
A brief description of the changes in this PR:

closes #150 

Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

### CODE REVIEW

**Comment by sculptex** [comment]
@bisakhmondal does it support offline mode?

**Comment by bisakhmondal** [comment]
> @bisakhmondal does it support offline mode?

Hey, good question. The create-wallet functionality depends on 0chain gosdk `CreateWallet` API

https://github.com/0chain/gosdk/blob/a4fee7ae103e201c158523deeb09a68a1b45976f/zcncore/wallet_base.go#L316-L336

So registering the wallet into miners' pool requires the user to be online. 

Btw, is it a requirement to support creating wallets offline?

**Comment by sculptex** [comment]
It's not a crucial requirement, just would be a nice option, but no worries if it would complicate thing.

The crucial requirement for offline wallet is in the recoverwallet function, that is users might need to generate zcn wallet/addresses using Ethereum compatible mnemonics, so as long as that function remains un-affected.

**Comment by dabasov** [comment]
I don't think we should register client on the miner, since it makes no sense, I'll start discussion on slack

**Comment by bisakhmondal** [comment]
> I don't think we should register client on the miner, since it makes no sense, I'll start discussion on slack

Done in PR #190. PTAL (cc @dabasov, @sculptex )

Closing the PR (created from personal fork, tests were unable to fetch GitHub secrets !?)

**Pull request closed without merging**
