### PR TITLE
Fix/config

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**
A brief description of the changes in this PR:
- Fix conditions for negative tokens

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/config  |
| gosdk  | staging  |
| zboxcli  | fix/min-lock-demand  |
| zwalletcli  | fix/config  |
| 0chain  | fix/config  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/config  |
| gosdk  | fix/min-lock-demand  |
| zboxcli  | fix/min-lock-demand  |
| zwalletcli  | fix/config  |
| 0chain  | fix/config  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/config  |
| gosdk  | fix/min-lock-demand  |
| zboxcli  | fix/min-lock-demand  |
| zwalletcli  | fix/config  |
| 0chain  | fix/config  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | fix/config  |
| gosdk  | fix/min-lock-demand  |
| zboxcli  | fix/min-lock-demand  |
| zwalletcli  | fix/config  |
| 0chain  | fix/config  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/min-lock-demand  |
| zboxcli  | fix/min-lock-demand  |
| zwalletcli  | fix/config  |
| 0chain  | fix/config  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
