### PR TITLE
Remove of mn-update-settings

### LINKED ISSUE #72: mn-update-settings duplicate of mn-update-node-settings
`mn-update-settings duplicate` is a duplicate of `mn-update-node-settings`. We should remove one of these two.

### PR DESCRIPTION
**Pull request by SinanEkm**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

### CODE REVIEW

**Review by Kishan-Dhakan — APPROVED** [review]

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Comment by dabasov** [comment]
can we remove command with longer name instead?

**Comment by SinanEkm** [comment]
> can we remove command with longer name instead?

I already removed the shorter one and edited the System Tests according to it. But, I can change the name of "**miner-node-update-settings**" to "**miner-update-settings**" or something similar/shorter. What do you say? @dabasov

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | removeOf-mn-update-settings  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | 72-mn-update-settings-duplicate-of-mn-update-node-settings  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
