### PR TITLE
Feature: synchronize DEX bridge interface change

### PR DESCRIPTION
**Pull request by YarikRevich**

### CODE REVIEW

**Comment by peterlimg** [comment]
@YarikRevich seems we haven't updated the gosdk

**Comment by YarikRevich** [comment]
Tests fail because automatically there gets chosen staging branch, which does not have requested changes. Firstly we need to merge PR in gosdk(even if zwalletcli build fails there) and then merge this one

**Comment by peterlimg** [comment]
We need to update the gosdk to the specific branch here to see if all could work well and pass the system tests. Otherwise merging gosdk directly could cause unexpected issues and break others.

**Comment by YarikRevich** [comment]
That's exactly what I've done. Custom branch commit is used for gosdk. CI envorinment replaces it with staging for tests, so they fail

**Comment by peterlimg** [comment]
Please check the go.mod cause I don't see any changes for gosdk there, perhaps you forget to commit.

**Comment by YarikRevich** [comment]
Exactly! You are right, forgot to push the commit.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  | feature/update-interface  |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Review by peterlimg — APPROVED** [review]
LGTM

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by YarikRevich** [comment]
Skipping tests because of the cyclic dependency with gosdk, which blocks the merge of the PR

**Pull request merged**
