### PR TITLE
Fix #99 trying to fix system test

### LINKED ISSUE #99: Update gosdk
There was an issue with the gosdk which caused the zbox to freeze in error scenario.
Fixing that made gosdk incompatible with the current zwalletcli we need to update it

### PR DESCRIPTION
**Pull request by samtholiya**
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
...

- [ ] https://github.com/0chain/zboxcli/pull/183
- [ ] https://github.com/0chain/gosdk/pull/402

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/registerFailDeadLock  |
| zboxcli  | fix/deadlock  |
| zwalletcli  | fix/gosdkupdate  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/registerFailDeadLock  |
| zboxcli  |  fix/deadlock  |
| zwalletcli  | fix/gosdkupdate  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
please update gosdk with latest commit on your branch. it should be 1b3247988866d5615a67ab312bc58a9f58904907

**Comment by Sriep** [comment]
You can use `go get github.com/0chain/gosdk@1b3247988866d5615a67ab312bc58a9f58904907`.

**Comment by Sriep** [comment]
Do we need this PR, It seems to point zbox at an out of date GoSDK commit? What PR is this meant to link to? I think we can close this.

**Comment by cnlangzi** [comment]
@samtholiya  please update gosdk with latest commit `bb5b797cf02c3e97f2d0e9f9e22a38619a9925d7`. and we can get this PR merged asap.thanks

**Comment by Sriep** [comment]
This seems to be out of date. There have been GoSDK commits after https://github.com/0chain/gosdk/pull/402 was merged, so this has become outdated. Pointing goSDK at `1b3247988866d5615a67ab312bc58a9f58904907` would risk losing subsequent work.

I am closing. If we need to repoint zbox I suggest opening a new PR that points go.mod to GoSDK head.

**Pull request closed without merging**
