### PR TITLE
Add command to register authorizers

### LINKED ISSUE #1602: Register authorizers
We should change `addAuthorier`
- This transaction type can only be executed by sc owner, should contain similar check
```
	if err := smartcontractinterface.AuthorizeWithOwner("register", func() bool {
		return gn.ZCNSC.OwnerId == t.ClientID
	}); err != nil {
		return "", err
	}
```
- this command should be added to zwalletcli, something like `auth-register` with operational wallet_id provided to it

### PR DESCRIPTION
**Pull request by boddumanohar**
A brief description of the changes in this PR:

fixes: https://github.com/0chain/0chain/issues/1602

```
./zwallet auth-register \
--url http://dev.0chain.net:32302 \
--client_key 347efa09e2156aa8ddb4a0a581cb8e6fed0d6b9c9c8d38d2f1fdd119069a3512de33665d17ed8e742497615e3f7c9ab5f0de747884e14836ac9496ce12299f81 \
--client_id 4a53cfa74eb600e973d28af1eedc9213bc3a4e9f3af4fd289bd441f642fb540a
```

the added authoriser URL can be checked by running
```
./zwallet bridge-list-auth

[
  {
    "id": "2f945f7310689f17afd8c8cb291e1e3ba21677243aa1d404a2293064e7983d60",
    "url": "http://dev.0chain.net:32301"
  },
  {
    "id": "4a53cfa74eb600e973d28af1eedc9213bc3a4e9f3af4fd289bd441f642fb540a",
    "url": "http://dev.0chain.net:32302"
  }
]
```
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- 0chain:
- Other: ...

### CODE REVIEW

**Comment by boddumanohar** [comment]
Currently blocked by moving [smartcontractinterface/interface.go#L34](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/smartcontractinterface/interface.go#L34) to [common](https://github.com/0chain/common). Will continue working once the interface is moved to [common](https://github.com/0chain/common)

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | register-authorizers  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | YES  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | register-authorizers  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
