### PR TITLE
Enable offline commands

### PR DESCRIPTION
**Pull request by shaktals**
A brief description of the changes in this PR:
Enable commands to be run offline, solves #106 

Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [x]  Merge your system tests PR to master AFTER merging this PR

### CODE REVIEW

**Comment by sculptex** [comment]
@shaktals I am not sure if current logic implementation should be default. That is `--register` needing to be specified for `recoverwallet`, when implementation has always been that to register is default. Perhaps register should be default and `--offline` be the option instead?

Also upon testing, both `version` and `recoverwallet` fail when there is no connection:-
```
0chain-core-sdk [INFO]   2022/04/12 11:14:39.132070 wallet.go:292: ******* Wallet SDK Version:v1.7.2-2-g3237f5c-dirty ******* (SetLogFile)
0chain-core-sdk [ERROR]  2022/04/12 11:14:39.133103 networkworker.go:46: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get "https://dev.0chain.net/dns/network": dial tcp: lookup dev.0chain.net: no such host}
UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get "https://dev.0chain.net/dns/network": dial tcp: lookup dev.0chain.net: no such host
get_network_details_error: Unable to get http request with error Get "https://dev.0chain.net/dns/network": dial tcp: lookup dev.0chain.net: no such host

```

**Comment by shaktals** [comment]
@sculptex I have fixed the recover cmd and now it has an `offline` flag as suggested.
However, to really enable it to run offline, I'd have to add that capability to gosdk `InitZCNSDK` method.
Should I dive into that?

**Comment by sculptex** [comment]
@shaktals as per other thread, it seems that the init is called before the command/parameters are even parsed.

I created alt. solution for recoverwallet but its still annoying that version cannot even be called offline. This is very unusual, a sysadmin would normally require to know versions of command tools without having to connect, even specify a network.

I think options are;

* Leave it (for now)
* Create special case for version (manually check for version command only and special handling prior to init)
* Refactor init/parse commands first

Edit: This issue also relates to and is probably more relevant to zboxcli since sysadmins would have more use for that but will leave here since they have same codebase

@cnlangzi @guruhubb @peterlimg ?

**Comment by shaktals** [comment]
Refactoring this so that `version` works offline I think it's easy. Offline `recoverwallet` would require changes on go-sdk.

**Comment by cnlangzi** [comment]
@sculptex   leave it with me. I will fix this issue next week.

**Comment by shaktals** [comment]
@cnlangzi feel free to take over this PR or close it then, thanks!

**Comment by cnlangzi** [comment]
@sculptex @shaktals  fixed and improved it on https://github.com/0chain/zwalletcli/pull/131

**Pull request closed without merging**
