### PR TITLE
Feature: modify "GetAuthorizers" function for the latest interface

### LINKED ISSUE #227: Feature: modify "GetAuthorizers" function for the latest interface

### PR DESCRIPTION
**Pull request by YarikRevich**
Associated PRs (Link as appropriate):
- gosdk: https://github.com/0chain/gosdk/pull/861

### CODE REVIEW

**Review by dabasov — CHANGES_REQUESTED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | feature/get_active_authorizer  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — COMMENTED** [review]
lgtm

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
