### PR TITLE
Fix/bridge breaks by wasm

### PR DESCRIPTION
**Pull request by cnlangzi**
fixed breaking by https://github.com/0chain/gosdk/pull/547

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/wasm_html_demo  |
| zboxcli  | staging  |
| zwalletcli  | fix/bridge_breaks_by_wasm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/expose_download_blocks_on_wasm  |
| zboxcli  | staging  |
| zwalletcli  | fix/bridge_breaks_by_wasm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by cnlangzi** [comment]
it is fixed by https://github.com/0chain/zwalletcli/pull/176

**Pull request closed without merging**
