### PR TITLE
Validate that createmswallet threshold is bigger than 0

### LINKED ISSUE #49: [FEATURE] Add validation to threshold param on createmswallet to avoid panic
on staging, zwallet cli dies with a panic when calling createmswallet with a threshold of 0
image

zwallet cli dies with a panic when calling createmswallet with a threshold of -1
image

Solution:
Add validation to threshold param to error out before trying to create a slice

### PR DESCRIPTION
**Pull request by shaktals**
Tasks to complete before merging PR:
- [x ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zwalletcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Resolves #49

### CODE REVIEW

**Comment by shaktals** [comment]
I'll work on the system tests to fix them.

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | validate-createmswallet-threshold  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | createmswallet-threshold-fix  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Comment by Kishan-Dhakan** [comment]
Thanks @shaktals! Client side validation on this is great as it reduces overhead. The panic itself is thrown in goSDK, since our SDK is open for others to use I'll raise a PR there to fix the underlying issue.

Edit: Fixed via: https://github.com/0chain/gosdk/pull/405

**Comment by cnlangzi** [comment]
@Kishan-Dhakan  @shaktals  this PR seems break `0Chain System Test` ? see https://github.com/0chain/zwalletcli/runs/5261772741?check_suite_focus=true. it should not be merged to `staging`. it blocks other PRs again.

**Comment by cnlangzi** [comment]
I know why it fails. @shaktals  you forget to merge https://github.com/0chain/system_test/pull/199 first.

**Comment by shaktals** [comment]
@cnlangzi I got this instruction to merge the feature branch first. But maybe I missed the point of doing the merges one right after another.

Selection_386

**Comment by cnlangzi** [comment]
> [0chain/system_test#199](https://github.com/0chain/system_test/pull/199)

@shaktals  Actually, you forget to merge https://github.com/0chain/system_test/pull/199 :)

**Comment by shaktals** [comment]
@cnlangzi I did not forget, I was asleep when @Kishan-Dhakan approved it.
Impossible to merge before approval right?

**Comment by shaktals** [comment]
@cnlangzi I did not forget anything.
When @Kishan-Dhakan approved it, I was taking care of other tasks.
You just got to it before I did.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Pull request merged**
